<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111; }
        .header { border-bottom: 1px solid #ddd; padding-bottom: 10px; margin-bottom: 12px; }
        .title { font-size: 18px; font-weight: 700; margin: 0 0 4px 0; }
        .meta { color: #555; font-size: 11px; margin: 0; }
        .section { margin-top: 14px; }
        .section h3 { font-size: 13px; margin: 0 0 8px 0; }
        .kpi { border: 1px solid #eee; border-radius: 8px; padding: 10px; }
        .row { display: table; width: 100%; }
        .col { display: table-cell; vertical-align: top; }
        .col-50 { width: 50%; }
        .label { color: #666; }
        .value { font-weight: 700; }
        .chart { border: 1px solid #eee; border-radius: 8px; padding: 10px; margin-top: 8px; }
        .chart img { width: 100%; height: auto; }
        ul { margin: 6px 0 0 18px; padding: 0; }
        li { margin: 4px 0; }
        .small { font-size: 11px; color: #666; }
    </style>
</head>
<body>

<div class="header">
    <p class="title">{{ $title }}</p>
    <p class="meta">
        Generated: {{ $generatedAt->format('d M Y, h:i A') }}
        @if(!empty($meta['range']))
            • Range: {{ $meta['range'] }}
        @endif
        @if(!empty($meta['filters']))
            • Filters: {{ $meta['filters'] }}
        @endif
        • Type: {{ ucwords(str_replace('_',' ', $reportType)) }}
    </p>
</div>

<div class="section">
    <h3>Summary</h3>
    <div class="kpi">
        @if(!empty($summaryData))
            @foreach($summaryData as $k => $v)
                <div style="margin-bottom:6px;">
                    <span class="label">{{ ucwords(str_replace('_',' ', $k)) }}:</span>
                    <span class="value">{{ $v }}</span>
                </div>
            @endforeach
        @else
            <p class="small">No summary available.</p>
        @endif
    </div>
</div>

<div class="section">
    <h3>Chart</h3>
    <div class="chart">
        <img src="{{ $chartImage }}" alt="Report Chart">
    </div>
</div>

@if(!empty($insights))
<div class="section">
    <h3>Insights</h3>
    <ul>
        @foreach($insights as $line)
            <li>{{ $line }}</li>
        @endforeach
    </ul>
</div>
@endif

<p class="small" style="margin-top:16px;">
    Generated by PadangPro Reporting Module.
</p>

</body>
</html>
